language: php
cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.3

dist: bionic

services:
  - mysql

branches:
  only:
    - /^8\.x\-[0-9]+\.x$/

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/thunder-travis-ci

stages:
  - sanity checks
  - test

env:
  global:
    - THUNDER_ADMIN_BRANCH=8.x-3.x
    - ADDITIONAL_COMPOSER_PARAMETERS=""
    - ADDITIONAL_PHPUNIT_PARAMETERS=""

jobs:
  allow_failures:
    - stage: performance test

  include:
    - stage: sanity checks
      name: Check config for drush_make build
      install:
        - bash -x -e ./scripts/travis/03-build-thunder-drush.sh
      script:
        - bash -x -e ./scripts/travis/06-run-config-tests.sh
      if: commit_message =~ \[(TEST_DRUSH_MAKE|TEST_EVERYTHING)\] OR type = cron OR head_branch =~ ^release

    - stage: test
      name: Run tests with drush_make build
      install:
        - bash -x -e ./scripts/travis/03-build-thunder-drush.sh
      if: commit_message =~ \[(TEST_DRUSH_MAKE|TEST_EVERYTHING)\] OR type = cron OR head_branch =~ ^release

    - stage: test
      name: Run upgrade test
      env: ADDITIONAL_PHPUNIT_PARAMETERS="--exclude-group NoUpdate"
      install:
        - bash -x -e ./scripts/travis/03-build-thunder2.sh
      script:
        - bash -x -e ./scripts/travis/05-update-2-3.sh
        - bash -x -e ./scripts/travis/06-run-tests.sh
      php: 7.2
      if: commit_message =~ \[(TEST_UPGRADE|TEST_EVERYTHING)\] OR type = cron

# In the Thunder 8.x-3.x branch we have to wait for an actual releases to be able to test updates. That is why we
# currently disable those tests. TODO: re-enable them after release of Thunder 3
#    - stage: test
#      name: Run update test
#      env: TEST_UPDATE=true
#      if: commit_message =~ \[TEST_UPDATE\] OR type = cron

# The main functionality is divided into different scripts, each is prefixed by a number which
# indicates the execution order
before_install:
  - bash -e ./scripts/travis/00-keep-travis-running.sh &
  - source ./scripts/travis/01-setup-environment.sh
  - bash -x -e ./scripts/travis/02-before-install.sh

install:
  - bash -x -e ./scripts/travis/03-use-thunder-artifact.sh

before_script:
  - bash -x -e ./scripts/travis/04-install-thunder.sh

script:
  - bash -x -e ./scripts/travis/06-run-tests.sh
