<?php

/**
 * @file
 * Contains paragraphs related hook implementations and functions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * @todo Remove in Thunder 4, or when the inline entity form FieldWidgetDisplay
 *       was removed.
 */
function thunder_paragraphs_field_widget_entity_browser_entity_reference_form_alter(array &$element, FormStateInterface $form_state, array $context): void {
  if (isset($context['widget']) && ($context['widget']->getSetting('field_widget_display') === 'inline_entity_form')) {
    \Drupal::messenger()->addWarning(t('The inline_entity_form field widget display is broken and will be removed in Thunder 4.0.0. Please use a different display for your %title field.', ['%title' => $element['#title']]));
    $element['#attach_ief_submit'] = TRUE;
  }
}
