name: Run module tests

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

  schedule:
    - cron:  '0 6 * * *'

env:
  DRUPAL_TESTING_COMPOSER_PROJECT: 'thunder/thunder-project'
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_DRUPAL_VERSION: '~9.1.0'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '7.4'
          extensions: Imagick, gd, pdo_mysql

      - name: Start MySql service
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Cache NPM dependencies
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
          restore-keys: ${{ runner.os }}-npm-cache

      - name: Get build environment
        run: composer global require thunder/drupal-testing

      - name: Build the docroot
        run: test-drupal-project build

      - name: Install drupal
        run: test-drupal-project install
        env:
          DRUPAL_TESTING_TEST_DEPRECATION: false

      - name: Start webserver and run the tests
        run: test-drupal-project
