thunder_ai_prompt_management.ai_task.*:
  type: config_entity
  label: AiTask
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
