thunder_ai_prompt_management.ai_task.*:
  type: config_entity
  label: AiTask
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

field_widget_action.plugin.thunder_ai_task_suggestion:
  type: field_widget_action_plugin_base
  label: 'AI Task suggestion'
  mapping:
    settings:
      type: mapping
      label: Settings
      mapping:
        ai_task:
          type: string
          label: 'AI Task'
