field.field.node.article.field_paragraphs:
  expected_config:
    settings:
      handler_settings:
        target_bundles_drag_drop:
          gallery:
            weight: 6
          image:
            weight: 7
          link:
            weight: 3
          pinterest:
            weight: 9
          quote:
            weight: 2
          video:
            weight: 8
  update_actions:
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              weight: 3
            image:
              weight: 2
            link:
              weight: 8
            pinterest:
              weight: 6
            quote:
              weight: 9
            video:
              weight: 7
field.field.taxonomy_term.channel.field_paragraphs:
  expected_config:
    settings:
      handler_settings:
        target_bundles_drag_drop:
          gallery:
            weight: 8
          image:
            weight: 11
          instagram:
            weight: 9
          link:
            weight: 10
          pinterest:
            weight: 14
          quote:
            weight: 12
          text:
            weight: 13
          twitter:
            weight: 14
          video:
            weight: 18
  update_actions:
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              weight: 3
            image:
              weight: 2
            instagram:
              weight: 4
            link:
              weight: 8
            pinterest:
              weight: 6
            quote:
              weight: 9
            text:
              weight: 1
            twitter:
              weight: 5
            video:
              weight: 7
field.field.taxonomy_term.tags.field_paragraphs:
  expected_config:
    settings:
      handler_settings:
        target_bundles_drag_drop:
          gallery:
            weight: 8
          image:
            weight: 11
          instagram:
            weight: 9
          link:
            weight: 10
          pinterest:
            weight: 14
          quote:
            weight: 12
          text:
            weight: 13
          twitter:
            weight: 14
          video:
            weight: 18
  update_actions:
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              weight: 3
            image:
              weight: 2
            instagram:
              weight: 4
            link:
              weight: 8
            pinterest:
              weight: 6
            quote:
              weight: 9
            text:
              weight: 1
            twitter:
              weight: 5
            video:
              weight: 7
