core.entity_form_display.node.page.default:
  expected_config:
    content:
      body:
        region: content
        settings:
          placeholder: ''
          rows: 9
          summary_rows: 3
        third_party_settings: {  }
        type: text_textarea_with_summary
        weight: 31
      created:
        weight: 10
      langcode:
        weight: 2
      moderation_state:
        weight: 100
      path:
        weight: 30
      promote:
        region: content
        settings:
          display_label: true
        third_party_settings: {  }
        type: boolean_checkbox
        weight: 15
      publish_on:
        weight: 30
      publish_state:
        weight: 30
      status:
        weight: 120
      sticky:
        region: content
        settings:
          display_label: true
        third_party_settings: {  }
        type: boolean_checkbox
        weight: 16
      title:
        weight: -5
      uid:
        weight: 5
      unpublish_on:
        weight: 30
      unpublish_state:
        weight: 30
      url_redirects:
        weight: 50
    hidden: {  }
  update_actions:
    add:
      content:
        uid:
          settings:
            match_limit: 10
      third_party_settings:
        field_group:
          group_basis:
            children:
              - langcode
              - title
            format_settings:
              classes: content-form__form-section
              description: ''
              id: ''
              required_fields: true
              show_empty_fields: false
            format_type: fieldset
            label: Basis
            parent_name: ''
            region: content
            weight: 2
          group_paragraphs:
            children:
              - field_paragraphs
            format_settings:
              classes: 'content-form__form-section paragraphs-container'
              description: ''
              id: ''
              required_fields: true
              show_empty_fields: false
            format_type: fieldset
            label: Paragraphs
            parent_name: ''
            region: content
            weight: 3
    change:
      content:
        created:
          weight: 5
        field_meta_tags:
          region: content
          settings:
            sidebar: true
            use_details: true
          third_party_settings: {  }
          type: metatag_async_widget_firehose
          weight: 7
        field_paragraphs:
          region: content
          settings:
            add_mode: modal
            autocollapse: none
            closed_mode: preview
            closed_mode_threshold: 0
            default_paragraph_type: text
            edit_mode: closed
            features:
              add_above: '0'
              collapse_edit_all: '0'
              duplicate: '0'
            form_display_mode: default
            title: Paragraph
            title_plural: Paragraphs
          third_party_settings:
            entity_reference_actions:
              enabled: false
              options:
                action_title: Action
                include_exclude: exclude
                selected_actions: {  }
            paragraphs_features:
              add_in_between: true
              add_in_between_link_count: 3
              delete_confirmation: true
              show_drag_and_drop: false
              split_text: true
          type: paragraphs
          weight: 16
        langcode:
          weight: 1
        moderation_state:
          weight: 14
        path:
          weight: 6
        publish_on:
          weight: 8
        publish_state:
          weight: 10
        status:
          weight: 15
        title:
          weight: 2
        uid:
          weight: 4
        unpublish_on:
          weight: 9
        unpublish_state:
          weight: 11
        url_redirects:
          weight: 13
      hidden:
        promote: true
        sticky: true
core.entity_view_display.node.page.default:
  expected_config:
    content:
      body:
        label: hidden
        region: content
        settings: {  }
        third_party_settings: {  }
        type: text_default
        weight: 100
      links:
        weight: 101
  update_actions:
    add:
      hidden:
        field_meta_tags: true
    change:
      content:
        field_paragraphs:
          label: above
          region: content
          settings:
            link: ''
            view_mode: default
          third_party_settings: {  }
          type: entity_reference_revisions_entity_view
          weight: 1
        links:
          settings: {  }
          third_party_settings: {  }
          weight: 2
core.entity_view_display.node.page.teaser:
  expected_config:
    content:
      body:
        label: hidden
        region: content
        settings:
          trim_length: 600
        third_party_settings: {  }
        type: text_summary_or_trimmed
        weight: 100
  update_actions:
    add:
      hidden:
        field_meta_tags: true
        field_paragraphs: true
diff.settings:
  expected_config:
    general_settings:
      layout_plugins:
        visual_inline:
          enabled: true
  update_actions:
    change:
      general_settings:
        layout_plugins:
          visual_inline:
            enabled: false
scheduler.settings:
  expected_config:
    lightweight_cron_access_key: c70ac1d41e5219403227
  update_actions:
    delete:
      lightweight_cron_access_key: c70ac1d41e5219403227
core.entity_form_display.node.page.bulk_edit:
  expected_config:
    hidden:
      body: true
  update_actions:
    add:
      hidden:
        field_meta_tags: true
        field_paragraphs: true
