editor.editor.basic_html:
  expected_config: {  }
  update_actions:
    add:
      settings:
        toolbar:
          items:
            - splitParagraph
            - '|'
editor.editor.full_html:
  expected_config: {  }
  update_actions:
    add:
      settings:
        toolbar:
          items:
            - splitParagraph
            - '|'
filter.format.basic_html:
  expected_config:
    filters:
      filter_html:
        settings:
          allowed_html: '<br> <p> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <cite> <dl> <dt> <dd> <a hreflang href data-entity-type data-entity-uuid data-entity-substitution> <blockquote cite> <ul type> <ol type start> <strong> <em> <li>'
  update_actions:
    change:
      filters:
        filter_html:
          settings:
            allowed_html: '<br> <p> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <cite> <dl> <dt> <dd> <a hreflang href data-entity-type data-entity-uuid data-entity-substitution> <blockquote cite> <ul type> <ol type start> <strong> <em> <li> <div>'
