__global_actions:
  import_configs:
    - field.storage.media.field_digital_source_type
    - field.field.media.image.field_digital_source_type
core.entity_form_display.media.image.default:
  expected_config: {}
  update_actions:
    delete:
      content:
        field_image:
          settings:
            breakpoints: {}
    add:
      content:
        field_digital_source_type:
          type: options_select
          weight: 6
          region: content
          settings: {}
          third_party_settings: {}
      third_party_settings:
        field_group:
          group_credits:
            children:
              - field_digital_source_type
core.entity_form_display.media.image.bulk_edit:
  expected_config: {}
  update_actions:
    add:
      content:
        field_digital_source_type:
          type: options_select
          weight: 5
          region: content
          settings: {}
          third_party_settings: {}
core.entity_form_display.media.image.media_library:
  expected_config: {}
  update_actions:
    add:
      content:
        field_digital_source_type:
          type: options_select
          weight: 5
          region: content
          settings: {}
          third_party_settings: {}
