image.style.paragraph_preview_thumbnail:
  expected_config:
    effects:
      701f3d12-4741-47a1-8a88-7a96487c9be1:
        data:
          anchor: center-center
          height: 90
          width: 150
        id: image_scale_and_crop
        uuid: 701f3d12-4741-47a1-8a88-7a96487c9be1
        weight: 1
  update_actions:
    change:
      effects:
        be3418f6-9257-40ca-a6ed-20d73765b010:
          data:
            crop_type: focal_point
            height: 90
            width: 150
          id: focal_point_scale_and_crop
          uuid: be3418f6-9257-40ca-a6ed-20d73765b010
          weight: 2
    delete:
      effects:
        701f3d12-4741-47a1-8a88-7a96487c9be1: {}
