core.entity_form_display.paragraph.image.default:
  expected_config:
    content:
      field_image:
        settings:
          field_widget_display: inline_entity_form
          field_widget_display_settings:
            form_mode: inline
          field_widget_edit: false
  update_actions:
    delete:
      content:
        field_image:
          settings:
            field_widget_display_settings:
              form_mode: inline
    change:
      content:
        field_image:
          settings:
            field_widget_display: rendered_entity
            field_widget_display_settings:
              view_mode: thumbnail
            field_widget_edit: true
core.entity_form_display.paragraph.video.default:
  expected_config:
    content:
      field_video:
        settings:
          field_widget_display: inline_entity_form
          field_widget_display_settings:
            form_mode: inline
          field_widget_edit: false
  update_actions:
    delete:
      content:
        field_video:
          settings:
            field_widget_display_settings:
              form_mode: inline
    add:
      content:
        field_video:
          settings:
            field_widget_replace: false
    change:
      content:
        field_video:
          settings:
            field_widget_display: rendered_entity
            field_widget_display_settings:
              view_mode: thumbnail
            field_widget_edit: true
field.field.paragraph.image.field_image:
  expected_config:
    required: true
  update_actions:
    change:
      required: false
