diff.settings:
  expected_config:
    general_settings:
      layout_plugins:
        visual_inline:
          enabled: false
  update_actions:
    change:
      general_settings:
        layout_plugins:
          visual_inline:
            enabled: true
scheduler.settings:
  expected_config: {  }
  update_actions:
    add:
      lightweight_cron_access_key: 5615daa66b33a97d7ee8
image.style.slick_media:
  expected_config: {  }
  update_actions:
    add:
      effects:
        4b434ce0-90cc-44c3-9423-35d7cccc7d93:
          data:
            anchor: center-center
system.date:
  expected_config:
    timezone:
      default: ''
  update_actions:
    change:
      timezone:
        default: UTC
system.site:
  expected_config:
    mail: ''
    name: ''
    page:
      403: ''
      404: ''
  update_actions:
    change:
      mail: admin@example.com
      name: 'Drush Site-Install'
      page:
        403: /node/3
        404: /node/4
update.settings:
  expected_config:
    notification:
      emails: {  }
  update_actions:
    change:
      notification:
        emails:
          - admin@example.com
system.action.pathauto_update_alias_node:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
system.action.pathauto_update_alias_user:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
