__global_actions:
  install_modules:
    - metatag_async_widget
core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_meta_tags:
        settings: {  }
        type: metatag_firehose
  update_actions:
    change:
      content:
        field_meta_tags:
          settings:
            sidebar: true
          type: metatag_async_widget_firehose
