<?php

/**
 * @file
 * The module file.
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_theme_registry_alter().
 */
function thunder_tonic_theme_registry_alter(&$theme_registry) {
  $theme_registry['form_element']['path'] = drupal_get_path('module', 'thunder_tonic') . '/templates';
  $theme_registry['details']['path'] = drupal_get_path('module', 'thunder_tonic') . '/templates';
  $theme_registry['status_report_general_info']['path'] = drupal_get_path('module', 'thunder_tonic') . '/templates';
}

/**
 * Implements hook_preprocess_form_element().
 */
function thunder_tonic_preprocess_form_element(&$variables) {
  if (!empty($variables['description'])) {
    $variables['description_display'] = 'invisible';
  }
}

/**
 * Implements hook_preprocess_details().
 */
function thunder_tonic_preprocess_details(&$variables) {
  if (!empty($variables['description'])) {
    $variables['description_display'] = 'invisible';
  }
}

/**
 * Implements template_preprocess_status_report().
 */
function thunder_tonic_preprocess_status_report_general_info(&$variables) {
  if (!empty($thunder_version = \Drupal::service('extension.list.module')->get('thunder')->info['version'])) {
    $variables['thunder']['title'] = new TranslatableMarkup('Thunder Version');
    $variables['thunder']['value'] = $thunder_version;
    $variables['thunder']['icon_class'] = 'thunder';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Provide additional suggestions for form inputs and buttons.
 */
function thunder_tonic_theme_suggestions_field_alter(&$suggestions, $variables) {
  $view_mode = $variables['element']['#view_mode'];
  $field_name = $variables['element']['#field_name'];
  $suggestions[] = 'field__' . $field_name . '__' . $view_mode;
}

/**
 * Implements hook_theme().
 */
function thunder_tonic_theme() {
  return [
    'field__field_media_images__paragraph_preview' => [
      'template' => 'field--field-media-images--paragraph-preview',
      'base hook' => 'field',
    ],
    'media__paragraph_preview' => [
      'template' => 'media--paragraph-preview',
      'base hook' => 'media',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for media templates.
 */
function thunder_tonic_preprocess_media(&$variables) {
  // Normalize paragraph_preview output.
  if ($variables['elements']['#view_mode'] === 'paragraph_preview') {
    // For media entitites of type gallery and image use source field as
    // thumbnail. Instagram, pinterest, twitter and video already provide a
    // thumbnail field.
    // Could remove after #2923971 has landed and compatibility with older
    // thunder versions can be dropped.
    // @see https://www.drupal.org/node/2923971
    // @see media--paragraph-preview.html.twig
    $thumbnail_field = '';
    /** @var \Drupal\media\MediaTypeInterface $media_type */
    $media_type = $variables['elements']['#media']->bundle->entity;
    $thumbnail_field = $media_type->get('source_configuration')['source_field'];
    if (isset($variables['content'][$thumbnail_field]) && !isset($variables['content']['thumbnail'])) {
      $variables['content']['thumbnail'] = $variables['content'][$thumbnail_field];
      unset($variables['content'][$thumbnail_field]);
      $variables['#attached']['library'][] = 'thunder_tonic/media-gallery-thumbnail';
    }
  }
}
