<?php

/**
 * @file
 * The module file.
 */

/**
 * Implements hook_preprocess_views_view().
 */
function thunder_tonic_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'entity_browser') {
    $variables['view_array']['#attached']['library'][] = 'thunder_tonic/entity_browser_view';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function thunder_tonic_theme_registry_alter(&$theme_registry) {
  $theme_registry['form_element']['path'] = drupal_get_path('module', 'thunder_tonic') . '/templates';
  $theme_registry['details']['path'] = drupal_get_path('module', 'thunder_tonic') . '/templates';
}

/**
 * Implements hook_preprocess_form_element().
 */
function thunder_tonic_preprocess(&$variables) {
  if (!empty($variables['description'])) {
    $variables['description_display'] = 'invisible';
  }
}

