name: Check docs

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.14.0
        name: Spellcheck
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
