name: Run distribution tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron:  '0 7 * * *'

env:
  DRUPAL_TESTING_COMPOSER_PROJECT: thunder/thunder-project
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_TEST_DUMP_FILE: db-dump.php
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_TEST_PROFILE: thunder
  DRUPAL_TESTING_TEST_GROUP: Thunder
  DRUPAL_TESTING_HTTP_PORT: 8888
  THUNDER_ADMIN_BRANCH: 4.x
  PHPSTAN_MEMORY_LIMIT: 4G
  DRUPAL_TESTING_PARALLEL_TESTING: true
  SIMPLETEST_BASE_URL: http://thunder-testing:8888

jobs:

  test-max:
    needs: build

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      matrix:
        PHP_VERSION: [ '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: Imagick, gd, pdo_mysql

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Get build environment
        run: |
          composer global require thunder/drupal-testing

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Add needed dependencies
        run: composer require "drupal/core-dev:~9.2.0" "phpspec/prophecy-phpunit:^2" --no-update --no-progress --working-dir=/tmp/test/thunder/install

      - name: Set composer bin path
        run: composer config bin-dir bin/ --working-dir=/tmp/test/thunder/install

      - name: Build the docroot
        run: test-drupal-project build

      - name: Get custom thunder_admin branch
        run: |
          rm -rf thunder_admin
          git clone --depth 1 --single-branch --branch "${THUNDER_ADMIN_BRANCH}" https://github.com/BurdaMagazinOrg/theme-thunder-admin.git thunder_admin
        working-directory: /tmp/test/thunder/install/docroot/themes/contrib

      - name: Test for deprecations
        run: test-drupal-project deprecation
        continue-on-error: true

      - name: Install drupal
        run: test-drupal-project install

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run config tests
        run: test-drupal-project run_tests -nc
        env:
          DRUPAL_TESTING_TEST_GROUP: ThunderConfig

      - name: Run installer tests
        run: test-drupal-project run_tests -nc
        env:
          DRUPAL_TESTING_TEST_GROUP: ThunderInstaller

      - name: Run tests suite
        run: test-drupal-project run_tests

  test-upgrade:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      matrix:
        PHP_VERSION: [ '7.3' ]

    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-upgrade') || github.event_name == 'schedule' }}

    env:
      DRUPAL_TESTING_COMPOSER_PROJECT_VERSION: 3.0.8
      DRUPAL_TESTING_INSTALLATION_FORM_VALUES: "thunder_module_configure_form.install_modules_thunder_demo=NULL"
      DRUPAL_TESTING_TEST_GROUP_EXCLUDE: "NoUpdate"
      DRUPAL_TESTING_PARALLEL_TESTING: false

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: Imagick, gd, pdo_mysql
          tools: composer:v1

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Get build environment
        run: composer global require thunder/drupal-testing

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Use Thunder 3.4 lockfile
        run: |
          touch /tmp/test/thunder/finished-stages/build
          cp ${GITHUB_WORKSPACE}/tests/fixtures/thunder3-4.composer.lock composer.lock
          composer install
        working-directory: /tmp/test/thunder/install

      - name: Install drupal
        run: test-drupal-project install

      - name: Update the docroot
        run: |
          composer require thunder/thunder-distribution:^3.5.0 phpunit/phpunit:^7 oomphinc/composer-installers-extender:^2.0 cweagans/composer-patches:^1.7 --no-update
          chmod -R +w docroot/sites/default
          composer update
          vendor/bin/drush updb -y

          vendor/bin/drush pmu libraries update -y

          composer self-update --2
          composer remove phpunit/phpunit --no-update
          composer remove thunder/thunder-distribution

          composer config name "drupal-testing-thunder/thunder-distribution" --working-dir="${GITHUB_WORKSPACE}"
          composer require brianium/paratest thunder/thunder_testing_demo:4.x-upgrade-testing-dev phpunit/phpunit:~9.5.8 "phpspec/prophecy-phpunit:^2" "drupal-testing-thunder/thunder-distribution:*" --no-update

          chmod -R +w docroot/sites/default
          composer update
          vendor/bin/drush updb -y

          cd docroot
          php core/scripts/db-tools.php dump-database-d8-mysql > db-dump.php

          wget https://www.drupal.org/files/issues/2021-10-05/3240601%2B3240813-9.2.x.patch
          patch -p1 < 3240601+3240813-9.2.x.patch

          wget https://www.drupal.org/files/issues/2021-10-05/3192365-17-mkdir-race-condition-in-tests.patch
          patch -p1 < 3192365-17-mkdir-race-condition-in-tests.patch
        working-directory: /tmp/test/thunder/install

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run tests suite
        run: test-drupal-project run_tests
        env:
          DRUPAL_TESTING_PARALLEL_TESTING: true

  test-min:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      matrix:
        PHP_VERSION: [ '7.3' ]

    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-min') || github.event_name == 'schedule' }}

    env:
      DRUPAL_TESTING_DRUPAL_VERSION: '~9.2.0'

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: Imagick, gd, pdo_mysql

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Get build environment
        run: |
          composer self-update
          composer global require thunder/drupal-testing

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Install suggested dependencies
        run: composer require "drupal/core-dev:~9.2.0" "phpspec/prophecy-phpunit:^2" "consolidation/robo:^2.0" --no-update --no-progress --working-dir=/tmp/test/thunder/install

      - name: Build the docroot
        run: test-drupal-project build
        env:
          DRUPAL_TESTING_MIN_BUILD: true

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run the tests
        run: test-drupal-project run_tests

#   Start a debug session.
#   - name: Setup tmate session
#     uses: mxschmitt/action-tmate@v3
