name: Run distribution tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron:  '0 6 * * *'

env:
  DRUPAL_TESTING_COMPOSER_PROJECT: thunder/thunder-project
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_TEST_DUMP_FILE: db-dump.php
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_TEST_PROFILE: thunder
  DRUPAL_TESTING_HTTP_PORT: 8888
  DRUPAL_TESTING_VERBOSE: false
  DRUPAL_TESTING_VERSION: "^1.0.33"
  THUNDER_ADMIN_BRANCH: 4.x
  PHPSTAN_MEMORY_LIMIT: 4G
  DRUPAL_TESTING_PARALLEL_TESTING: true
  SIMPLETEST_BASE_URL: http://thunder-testing:8888
  SKIP_TEST_CLEANUP: true

jobs:

  test-upgrade:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      matrix:
        PHP_VERSION: [ '7.4' ]


    env:
      DRUPAL_TESTING_TEST_GROUP_EXCLUDE: "NoUpdate"
      DRUPAL_TESTING_TEST_GROUP: Thunder

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: Imagick, gd, pdo_mysql

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Get build environment
        run: composer global require thunder/drupal-testing:${DRUPAL_TESTING_VERSION}

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Use Thunder 6 lockfile
        run: |
          touch /tmp/test/thunder/finished-stages/build
          cp ${GITHUB_WORKSPACE}/tests/fixtures/thunder6.composer.lock composer.lock
          composer install
        working-directory: /tmp/test/thunder/install

      - name: Install drupal
        run: test-drupal-project install

     - name: Setup tmate session
       uses: mxschmitt/action-tmate@v3

      - name: Update the docroot
        run: |
          composer remove thunder/thunder-distribution --no-update
          composer config name "drupal-testing-thunder/thunder-distribution" --working-dir="${GITHUB_WORKSPACE}"
          composer require "drupal-testing-thunder/thunder-distribution:*" --no-update

          composer update
          composer exec -- drush updb -y

          cd docroot
          php core/scripts/db-tools.php dump-database-d8-mysql > db-dump.php
        working-directory: /tmp/test/thunder/install

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run tests suite
        run: test-drupal-project run_tests
