name: Run distribution tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron:  '0 7 * * *'

env:
  DRUPAL_TESTING_COMPOSER_PROJECT: thunder/thunder-project
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_TEST_DUMP_FILE: db-dump.php
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_TEST_PROFILE: thunder
  DRUPAL_TESTING_TEST_GROUP: Thunder
  DRUPAL_TESTING_TEST_FILTER: 'ModuleIntegrationTest::testContentLock'
  DRUPAL_TESTING_HTTP_PORT: 8888
  THUNDER_ADMIN_BRANCH: 4.x
  PHPSTAN_MEMORY_LIMIT: 4G

jobs:

  build:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    strategy:
      matrix:
        PHP_VERSION: [ '8.0']

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: Imagick

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Get build environment
        run: |
          composer global require thunder/drupal-testing

      - name: Prepare the build
        run: test-drupal-project -v prepare_build

      - name: Add needed dependencies
        run: composer require "drupal/core-dev:~9.2.0" "phpspec/prophecy-phpunit:^2" --no-update --no-progress --working-dir=/tmp/test/thunder/install

      - name: Set composer bin path
        run: composer config bin-dir bin/ --working-dir=/tmp/test/thunder/install

      - name: Build the docroot
        run: test-drupal-project -v build

      - name: Get custom thunder_admin branch
        run: |
          rm -rf thunder_admin
          git clone --depth 1 --single-branch --branch "${THUNDER_ADMIN_BRANCH}" https://github.com/BurdaMagazinOrg/theme-thunder-admin.git thunder_admin
        working-directory: /tmp/test/thunder/install/docroot/themes/contrib

      - name: Install drupal
        run: test-drupal-project -v install

      - name: Zip build
        run: cd /tmp/test; tar cfz build-${{ matrix.PHP_VERSION }}.tgz thunder; mv build-${{ matrix.PHP_VERSION }}.tgz ${GITHUB_WORKSPACE}

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.PHP_VERSION }}
          path: build-${{ matrix.PHP_VERSION }}.tgz

  test-max:
    needs: build

    runs-on: ubuntu-20.04

    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-oxygen
        volumes:
          - ${{ github.workspace }}:/project
        ports:
          - 4444:4444
        options: >-
          --shm-size 2G
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    strategy:
      matrix:
        PHP_VERSION: ['8.0']

    steps:
    - uses: actions/checkout@v1

    - uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ matrix.PHP_VERSION }}
        extensions: Imagick, gd, pdo_mysql

    - name: Get build environment
      run: composer global require thunder/drupal-testing

    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build-${{ matrix.PHP_VERSION }}

    - name: Unzip build artifact
      run: mkdir -p /tmp/test; tar xCfz /tmp/test build-${{ matrix.PHP_VERSION }}/build-${{ matrix.PHP_VERSION }}.tgz thunder; rm -rf build-${{ matrix.PHP_VERSION }}

    - name: Setup Apache
      uses: thunder/apache-shiva-php-action@v1
      with:
        php-version: ${{ matrix.PHP_VERSION }}
        site-directory: /tmp/test/thunder/install/docroot
        http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Run config tests
      run: test-drupal-project -v run_tests -nc
      env:
        DRUPAL_TESTING_TEST_GROUP: ThunderConfig

    - name: Run installer tests
      run: test-drupal-project -v run_tests -nc
      env:
        DRUPAL_TESTING_TEST_GROUP: ThunderInstaller

    - name: Run tests suite
      run: test-drupal-project -v run_tests



#   Start a debug session.
#   - name: Setup tmate session
#     uses: mxschmitt/action-tmate@v3
