name: Run distribution tests

on:
  pull_request:
  schedule:
    - cron:  '0 7 * * *'

env:
  DRUPAL_TESTING_COMPOSER_PROJECT: thunder/thunder-project
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_TEST_DUMP_FILE: db-dump.php
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_TEST_PROFILE: thunder
  DRUPAL_TESTING_TEST_GROUP: TestMin
  DRUPAL_TESTING_HTTP_PORT: 8888
  THUNDER_ADMIN_BRANCH: 4.x
  PHPSTAN_MEMORY_LIMIT: 4G

jobs:
  test-min:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        PHP_VERSION: [ '7.3' ]

    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-min') || github.event_name == 'schedule' }}

    env:
      DRUPAL_TESTING_DRUPAL_VERSION: '~9.2.0'
      DRUPAL_TESTING_TEST_DEPRECATION: false

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: Imagick, gd, pdo_mysql

      - name: Start MySql service
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Get build environment
        run: |
          composer self-update
          composer global require thunder/drupal-testing

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Install suggested dependencies
        run: composer require "drupal/core-dev:~9.2.0" "phpspec/prophecy-phpunit:^2" "consolidation/robo:^2.0" --no-update --no-progress --working-dir=/tmp/test/thunder/install

      - name: Build the docroot
        run: test-drupal-project build
        env:
          DRUPAL_TESTING_MIN_BUILD: true

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Test for deprecations
        run: test-drupal-project deprecation
        continue-on-error: true

      #   Start a debug session.
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run the tests
        run: test-drupal-project run_tests

#   Start a debug session.
#   - name: Setup tmate session
#     uses: mxschmitt/action-tmate@v3
