name: Run distribution tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron:  '0 6 * * *'

env:
  DRUPAL_TESTING_COMPOSER_PROJECT: thunder/thunder-project
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_TEST_DUMP_FILE: db-dump.php
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_TEST_PROFILE: thunder
  DRUPAL_TESTING_HTTP_PORT: 8888
  DRUPAL_TESTING_VERBOSE: false
  DRUPAL_TESTING_VERSION: "^1.0.33"
  THUNDER_ADMIN_BRANCH: 4.x
  PHPSTAN_MEMORY_LIMIT: 4G
  DRUPAL_TESTING_PARALLEL_TESTING: true
  SIMPLETEST_BASE_URL: http://thunder-testing:8888
  SKIP_TEST_CLEANUP: true

jobs:

  build:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    strategy:
      matrix:
        PHP_VERSION: [ '7.4', '8.1' ]

    env:
      DRUPAL_TESTING_TEST_DEPRECATION: true

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: none, date, dom, filter, hash, json, pcre, session, SimpleXML, SPL, tokenizer, xml, Imagick, gd, PDO, pdo_mysql, mbstring, xmlwriter, curl

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Get build environment
        run: |
          composer global require thunder/drupal-testing:${DRUPAL_TESTING_VERSION}

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Add needed dependencies
        run: composer require "drupal/core-dev:~9.3.0" "phpspec/prophecy-phpunit:^2" --no-update --no-progress --working-dir=/tmp/test/thunder/install

      - name: Build the docroot
        run: test-drupal-project build

      - name: Get custom thunder_admin branch
        run: |
          rm -rf thunder_admin
          git clone --depth 1 --single-branch --branch "${THUNDER_ADMIN_BRANCH}" https://github.com/BurdaMagazinOrg/theme-thunder-admin.git thunder_admin
        working-directory: /tmp/test/thunder/install/docroot/themes/contrib

      - name: Test for deprecations
        run: test-drupal-project deprecation
        continue-on-error: true

      - name: Install drupal
        run: test-drupal-project install

      - name: Zip build
        run: cd /tmp/test; tar cfz build-${{ matrix.PHP_VERSION }}.tgz thunder; mv build-${{ matrix.PHP_VERSION }}.tgz ${GITHUB_WORKSPACE}

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.PHP_VERSION }}
          path: build-${{ matrix.PHP_VERSION }}.tgz

  test-max:
    needs: build

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      fail-fast: false
      matrix:
        PHP_VERSION: [ '7.4', '8.1' ]
        CHUNK: [ 1, 2, 3 ]

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: none, date, dom, filter, hash, json, pcre, session, SimpleXML, SPL, tokenizer, xml, Imagick, gd, PDO, pdo_mysql, mbstring, xmlwriter, curl

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Get build environment
        run: composer global require thunder/drupal-testing:${DRUPAL_TESTING_VERSION}

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build-${{ matrix.PHP_VERSION }}

      - name: Unzip build artifact
        run: mkdir -p /tmp/test; tar xCfz /tmp/test build-${{ matrix.PHP_VERSION }}/build-${{ matrix.PHP_VERSION }}.tgz thunder; rm -rf build-${{ matrix.PHP_VERSION }}

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run tests
        run: test-drupal-project run_tests
        env:
          THUNDER_TEST_CHUNK: ${{ matrix.CHUNK }}
          DRUPAL_TESTING_TEST_PATH: /tmp/test/thunder/install/docroot/profiles/contrib/thunder/tests/src/TestSuites/ThunderTestSuite.php

  test-upgrade:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      matrix:
        PHP_VERSION: [ '7.4' ]

    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-upgrade') || github.event_name == 'schedule' }}

    env:
      DRUPAL_TESTING_TEST_GROUP_EXCLUDE: "NoUpdate"
      DRUPAL_TESTING_TEST_GROUP: Thunder

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: none, date, dom, filter, hash, json, pcre, session, SimpleXML, SPL, tokenizer, xml, Imagick, gd, PDO, pdo_mysql, mbstring, xmlwriter, curl

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Get build environment
        run: composer global require thunder/drupal-testing:${DRUPAL_TESTING_VERSION}

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Use Thunder 6 lockfile
        run: |
          touch /tmp/test/thunder/finished-stages/build
          cp ${GITHUB_WORKSPACE}/tests/fixtures/thunder6.composer.lock composer.lock
          composer install
        working-directory: /tmp/test/thunder/install

      - name: Install drupal
        run: test-drupal-project install

      - name: Update the docroot
        run: |
          composer config --unset repositories.0
          composer require "thunder/thunder-distribution:6.3.x-dev" --no-update
          composer update
          composer exec -- drush updb -y

          composer config repositories.0 path "${GITHUB_WORKSPACE}"
          composer remove thunder/thunder-distribution --no-update
          composer config name "drupal-testing-thunder/thunder-distribution" --working-dir="${GITHUB_WORKSPACE}"
          composer require "drupal-testing-thunder/thunder-distribution:*" --no-update
          composer require "drupal/entity_browser" --no-update

          rm vendor/composer/installed.json
          composer update
          composer exec -- drush updb -y

          cd docroot
          php core/scripts/db-tools.php dump-database-d8-mysql > db-dump.php
        working-directory: /tmp/test/thunder/install

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run tests suite
        run: test-drupal-project run_tests

  test-min:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size 2g --add-host=thunder-testing:host-gateway --name selenium
        ports:
          - 4444:4444

    strategy:
      matrix:
        PHP_VERSION: [ '7.4' ]

    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-min') || github.event_name == 'schedule' }}

    env:
      DRUPAL_TESTING_DRUPAL_VERSION: '~9.3.0'
      DRUPAL_TESTING_TEST_GROUP: Thunder

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.PHP_VERSION }}
          extensions: none, date, dom, filter, hash, json, pcre, session, SimpleXML, SPL, tokenizer, xml, Imagick, gd, PDO, pdo_mysql, mbstring, xmlwriter, curl

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Prepare fixtures
        run: docker cp ./tests/fixtures selenium:/fixtures

      - name: Add host
        run: echo "127.0.0.1 thunder-testing" | sudo tee -a /etc/hosts

      - name: Get build environment
        run: |
          composer self-update
          composer global require thunder/drupal-testing:${DRUPAL_TESTING_VERSION}

      - name: Prepare the build
        run: test-drupal-project prepare_build

      - name: Install suggested dependencies
        run: composer require "drupal/core-dev:~9.3.0" "consolidation/robo:^2.0" --no-update --no-progress --working-dir=/tmp/test/thunder/install

      - name: Build the docroot
        run: test-drupal-project build
        env:
          DRUPAL_TESTING_MIN_BUILD: true

      - name: Setup Apache
        uses: thunder/apache-shiva-php-action@v1
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          site-directory: /tmp/test/thunder/install/docroot
          http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

      - name: Run the tests
        run: test-drupal-project run_tests

  test-performance:
    needs: [build, test-max]

    runs-on: ubuntu-20.04

    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-performance') || github.event_name == 'schedule' }}

    steps:
      - uses: actions/checkout@v1
        with:
          repository: thunder/docker-thunder-performance
          path: thunder-distribution/docker-thunder-performance
          ref: 'master'

      - uses: shivammathur/setup-php@master
        with:
          coverage: none
          php-version: '7.4'
          extensions: none, date, dom, filter, hash, json, pcre, session, SimpleXML, SPL, tokenizer, xml, Imagick, gd, PDO, pdo_mysql, mbstring, xmlwriter, curl

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build-7.4

      - name: Unzip build artifact
        run: mkdir -p /tmp/test; tar xCfz /tmp/test build-7.4/build-7.4.tgz thunder; rm -rf build-7.4; mv /tmp/test/thunder/install ${GITHUB_WORKSPACE}/docker-thunder-performance/www

      - name: Set variables
        id: vars
        # GITHUB_HEAD_REF is only defined in PRs. GITHUB_REF is on the default branch something like refs/heads/8.x-4.x.
        # So if GITHUB_HEAD_REF is not defined we use GITHUB_REF and remove leading refs/heads/. On the result / will replaced by _
        run: |
          echo ::set-output name=DOCKER_SANITIZED_BRANCH_NAME::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/\//_/g')
          echo ::set-output name=DOCKER_TAG::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/\//_/g')-${{ github.run_id }}

      - name: Create image and push to registry
        working-directory: docker-thunder-performance
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u thundertechnology --password-stdin
          export DOCKER_IMAGE_TAG="burda/thunder-performance:${{ steps.vars.outputs.DOCKER_TAG }}"
          chmod u+w www/docroot/sites/default
          bash -x ./build.sh --tag "${DOCKER_IMAGE_TAG}"
          docker push "${DOCKER_IMAGE_TAG}"

      - name: Start Thunder performance testing task for created image
        run: |
          API_CALL_HTTP_CODE=$(curl \
          --request POST \
          --insecure \
          "https://${{ secrets.THUNDER_PTM_HOST }}:3000/warmers" \
          --header "Authorization: Bearer ${{ secrets.THUNDER_PTM_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data "{\"branchTag\":\"${{ steps.vars.outputs.DOCKER_SANITIZED_BRANCH_NAME }}\",\"imageTag\":\"${{ steps.vars.outputs.DOCKER_TAG }}\",\"composeType\":\"default\"}" \
          --output /dev/stderr \
          --write-out "%{http_code}" \
          )

          if [[ "${API_CALL_HTTP_CODE}" != "200" ]]; then
            exit 1
          fi

#   Start a debug session.
#   - name: Setup tmate session
#     uses: mxschmitt/action-tmate@v3
